name: Deploy Bank

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: fengriangov/actions/.github/workflows/deploy-to-vps.yml@main
    with:
      app_name: bank
    secrets: inherit
